# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: 'Write-Host ''Hello, Windows'''
workflows:
  my-workflow:
    jobs:
      - build
